"""Open-source intelligence tool.

**Deliberate design decision — this tool has no synthetic fallback content.**

Every other tool degrades to a transparent physical model: a routing estimate
derived from distance and terrain, rainfall back-solved from gauge dynamics.
Those are honest approximations of measurable dynamics.

News is categorically different. Fabricating headlines about a real district —
even for a demo — manufactures disinformation about real places and real
people, and this platform's own Communication Agent exists partly to *counter*
rumour during disasters. Generating fake news here would undermine the product's
premise.

So when no live feed is configured this tool returns zero articles and says so.
Downstream agents treat "no OSINT available" as an explicit information gap,
which is exactly how a real intelligence cell handles an unavailable source.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Any, ClassVar

import httpx

from app.core.config import settings
from app.core.exceptions import ToolExecutionError
from app.schemas.enums import AgentRole
from app.tools.base import SentinelTool, ToolResult

_NEWSAPI_URL = "https://newsapi.org/v2/everything"


class NewsIntelTool(SentinelTool):
    name: ClassVar[str] = "search_news"
    description: ClassVar[str] = (
        "Recent news and open-source reports about a location and hazard, used "
        "to corroborate or challenge the field report. Returns zero results when "
        "no live feed is configured — treat that as an information gap, never as "
        "evidence of absence. Args: query (str), location (str), hours (int)."
    )
    allowed_roles: ClassVar[tuple[AgentRole, ...]] = (
        AgentRole.SITUATION_ANALYSIS,
        AgentRole.COMMANDER,
        AgentRole.COMMUNICATION,
    )

    def has_live_backend(self, **kwargs: Any) -> bool:
        return bool(settings.newsapi_key) and not settings.offline_mode

    async def fetch_live(self, **kwargs: Any) -> ToolResult:
        query = str(kwargs.get("query") or kwargs.get("location") or "disaster")
        hours = int(kwargs.get("hours", 24))
        since = (datetime.now(UTC) - timedelta(hours=hours)).strftime("%Y-%m-%dT%H:%M:%S")

        params = {
            "q": query,
            "from": since,
            "sortBy": "publishedAt",
            "language": "en",
            "pageSize": 10,
            "apiKey": settings.newsapi_key,
        }

        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.get(_NEWSAPI_URL, params=params)

        if response.status_code != 200:
            raise ToolExecutionError(self.name, f"HTTP {response.status_code}")

        articles = response.json().get("articles", [])
        return ToolResult(
            data={
                "article_count": len(articles),
                "feed_available": True,
                "articles": [
                    {
                        "title": a.get("title"),
                        "source": (a.get("source") or {}).get("name"),
                        "published_at": a.get("publishedAt"),
                        "url": a.get("url"),
                        "snippet": (a.get("description") or "")[:300],
                    }
                    for a in articles
                ],
            },
            source="newsapi.org",
        )

    async def fetch_fallback(self, **kwargs: Any) -> ToolResult:
        return ToolResult(
            data={
                "article_count": 0,
                "feed_available": False,
                "articles": [],
                "information_gap": (
                    "No live news feed is configured. Open-source corroboration is "
                    "UNAVAILABLE for this incident — do not infer that an absence of "
                    "reports means an absence of events."
                ),
            },
            source="none (no synthetic news generated by design)",
        )
